### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'allPermissions')

### ISSUE THREAD

**Issue by PandhuWibowo** [strapi-community/strapi-provider-upload-google-cloud-storage#123]
Hi @Lith ,

Do you know what happened to my media?
I'm using Strapi v4.0.5 recently

My media show blank out page

<a href="https://ibb.co/KrFJmHX"><img src="https://i.ibb.co/d5GR7yr/Screenshot-from-2022-03-09-13-23-28.png" alt="Screenshot-from-2022-03-09-13-23-28" border="0"></a>

Maybe you can help me, what happened to my app?
Thanks in advance

**Comment by Lith** [comment]
Hi @PandhuWibowo 

The error message is displayed a "permissions media error", have you enabled right with permissions plugins for your user ?

Also, this problem need to be report to Strapi team, because my plugins concern upload system but not the upload management.

Thanks ☺️
