### ISSUE TITLE
API returns bucket url instead of cdn url

### ISSUE THREAD

**Issue by rrubio** [strapi-community/strapi-provider-upload-google-cloud-storage#132]
Under development i used the default cloudstorage url -

`"baseUrl: 'https://storage.googleapis.com/{bucket-name}'". `

Works perfectly, however, i'm ready to go into production now, i've created a load balancer cdn -

`"media.mysite.com".`

Updating "baseUrl" to "media.mysite.com" does not change the return data "url" containing the original URL (example below) - 

`https://storage.googleapis.com/my-bucket/my-folder/my-image.jpg `

Any help is much appreciated.

**Comment by Lith** [comment]
Hi @rrubio,

In fact, for each media, the relative url is saved in database, so all "old" files must be renamed manually by updating `url` field of media table.
New uploaded files will have the new url name (in theory, this is working for me with Strapi 3).

Thanks

**Comment by darrenhaken** [comment]
Did you solve this?

**Comment by rrubio** [comment]
@Lith apologies for the late response. The issue for me was related to not using the new "deep" population.  I ended up using this plugin - https://market.strapi.io/plugins/strapi-plugin-populate-deep
