### ISSUE TITLE
Content-Disposition is set with possibly invalid value

### ISSUE THREAD

**Issue by Fryuni** [strapi-community/strapi-provider-upload-google-cloud-storage#135]
**Describe the bug**

The `Content-Disposition` metadata is being set with the original name of the file, without any modifications.
https://github.com/strapi-community/strapi-provider-upload-google-cloud-storage/blob/1835a16855ca0c08ecbf6fb80caac4f9ae105b33/lib/provider.js#L185

This metadata is returned as an HTTP header, [whose value](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2) should be [a USASCII character](https://datatracker.ietf.org/doc/html/rfc7230#section-1.2). Some clients ignore this restriction and accept non-ASCII characters, but compliant clients will fail when trying to access the image.
For example, Node's new `fetch` function is compliant and will fail when trying to retrieve an image with an invalid header

This value should be normalized just like the upload file name.

**To Reproduce**
1. Rename an image locally to a name with non-ASCII characters. (In our case it was `â`)
2. Upload the image
3. Try to download it with Node's `fetch` function (In our case it was called internally by Next.js)

**Expected behavior**
The image should be uploaded with valid values.

**Screenshots**

Error from Node's new `fetch` function:
![image](https://user-images.githubusercontent.com/11063910/173673274-0a2a2115-36e8-4b22-b7d5-fc9682f887a0.png)

**Comment by Lith** [comment]
Hi @Fryuni 

Thanks for this bug report, and thanks to @denis-rossati for his PR
We will merge it ASAP and release a new version of this plugin.

Best.
