### ISSUE TITLE
Provider string in npm documentation is depricated

### ISSUE THREAD

**Issue by MartinSchwarzmaier** [strapi-community/strapi-provider-upload-google-cloud-storage#138]
**Describe the bug**
The example configurations provider string in the npm documentation is still `strapi-provider-upload-google-cloud-storage` while it should be `@strapi-community/strapi-provider-upload-google-cloud-storage`.

**To Reproduce**
1. Open https://www.npmjs.com/package/@strapi-community/strapi-provider-upload-google-cloud-storage
2. Go to "Setting up the configuration file"

**Expected behavior**
The documentation should have the correct provider string in its example.

![Bildschirmfoto vom 2022-07-01 08-42-33](https://user-images.githubusercontent.com/79309052/176839649-0f2d500c-dd09-44b0-92a0-0314a677f574.png)

**Comment by Lith** [comment]
Hello @MartinSchwarzmaier 

I've forgot to publish new NPM release with latest update of this repository.
This is fixed now with release 4.2.3

Thanks,
