### ISSUE TITLE
GCP Permission - storage.buckets.get is required for the plugin to work. 

### ISSUE THREAD

**Issue by darrenhaken** [strapi-community/strapi-provider-upload-google-cloud-storage#139]
**Describe the bug**

storage.buckets.get - why does it require this permission, by default we give our services Storage Object Admin as the apps control content, not the bucket itself.  In order to get this plugin to work, we have had to elevate that to Storage Admin

**Comment by Lith** [comment]
Hi @darrenhaken,

Feel free to submit PR update with our needed.

Thanks,

**Comment by sorokya** [comment]
@darrenhaken Found that setting `skipCheckBucket: true` in the plugin config seems to fix this
