### ISSUE TITLE
Files are not uploaded as public even with publicFiles at true

### ISSUE THREAD

**Issue by femtozer** [strapi-community/strapi-provider-upload-google-cloud-storage#141]
First, thank you for this nice provider :)
I'm using a fine grained ACL bucket.
My config is:

``` js
module.exports = ({ env }) => ({
    upload: {
      config: {
        provider: '@strapi-community/strapi-provider-upload-google-cloud-storage',
        providerOptions: {
            bucketName: env('GCS_BUCKET_NAME'),
            serviceAccount: env.json('GCS_SERVICE_ACCOUNT'),
            publicFiles: true,
            uniform: false,
        },
      },
    },
});
```

Uploaded files are not set as public in the bucket.

I think the issue come from this line:
https://github.com/strapi-community/strapi-provider-upload-google-cloud-storage/blob/a6b593744d151c9890156182ca1f1d8c5009e7c8/lib/provider.js#L236

fileAttributes needs to be set as a parameter:
``` js
file.stream.pipe(bucketFile.createWriteStream(fileAttributes)).on('finish', () => { 
```

You can find the documentation [here](https://googleapis.dev/nodejs/storage/latest/File.html#createWriteStream) if needed.

**Comment by femtozer** [comment]
I created a PR https://github.com/strapi-community/strapi-provider-upload-google-cloud-storage/pull/142

**Comment by Lith** [comment]
Hello @femtozer,

Thanks for your contribution ! 
I will merge it as soon as possible, you just need to add your signature.

Thanks

**Comment by femtozer** [comment]
Hello @Lith 
I don't know if there was an other way but I had to create a new PR #143 to have the commit verified.

**Comment by konstantinasj** [comment]
@femtozer @Lith Hi, any updates on this fix?

**Comment by Srihariaditha** [comment]
@femtozer @Lith Any update on this fix!!

**Comment by AlexSwtlsk** [comment]
Any idea when the #143 will be merged ?

**Comment by alumedot** [comment]
Same problem here, any updates?

**Comment by Tsovak** [comment]
@Lith  let's merge #143

**Comment by Tsovak** [comment]
another reason why it can happen is that your all files are public unavailable. you have to make it accessible for everybody   
https://cloud.google.com/storage/docs/access-control/making-data-public

**Comment by pccatdmc** [comment]
Strapi V4.2.x is works fine and update Strapi V4.3.x  upload image to library, Internal Server Error and 500
I'm not sure if it's a plugin issue ?

**Comment by Lith** [comment]
Sorry about the delay... I would like more people manage this repository but I'm alone and I was really too busy during last month :'( 
I've merge #143 and I will publish new release on NPM.

Please apologies 😢

**Comment by alumedot** [comment]
Thanks, @Lith 🙌
