### ISSUE TITLE
Uploading in production not working

### ISSUE THREAD

**Issue by TriPSs** [strapi-community/strapi-provider-upload-google-cloud-storage#144]
**Describe the bug**
When uploading a file in production the response says the file is uploaded but it can't be found in the bucket.

**To Reproduce**
1. Upload file
2. Get "file uploaded message"
3. Thumbnail does not work
4. Refresh
5. Thumbnail still does not work, file is not found in bucket at all

**Expected behavior**
That the file is correctly uploaded

**Comment by TriPSs** [comment]
Finally got it locally to, after some debugging it throws this error

```
error {
  code: 400,
  message: 'Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access',
  errors: [
    {
      message: 'Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access',
      domain: 'global',
      reason: 'invalid'
    }
  ]
}
```

Seems that `streamFileUpload().catch(console.error)` does not log it correctly, changing it to following does:
```
        await streamFileUpload().catch((err) => {
          console.error(err)
        });
```

**Comment by TriPSs** [comment]
My proposed solution:

```ts
        const streamFileUpload = () => new Promise((resolve, reject) => {
          file.stream.pipe(bucketFile.createWriteStream(fileAttributes))
            .on('error', (error) => {
              reject(error)
            })
            .on('finish', () => {
              // The file upload is complete
              console.log(`File successfully uploaded to ${file.url}`)

              resolve()
            })
        })

        await streamFileUpload()
```

This fixes 2 issues:
1. Errors not being logged to the console
2. Initial thumbnail not working, refresh required

**Comment by lcottingham** [comment]
+1 for this.
Stuck on Strapi v `2.3.6`, and cannot update without breaking this plugin. Upload behaviour works as expected on `2.3.6` and is logged in the console, beyond this `2.3.7` and `2.3.8`, the file logs an upload by Strapi, but not to Google.

`File successfully uploaded to https://storage.googleapis.com/.....` is missing in the logs and file is not uploaded.

No context was provided on the error.

**Comment by lcottingham** [comment]
> @lcottingham maybe setting `uniform: true` will also fix the issue for you?

It did yes, but was frustrating to have no contextual errors in the logs to point me in the right direction. The error and solution are documented, but the error isn't logged currently (without your proposed solution). Anyway, thanks for helping resolve.
