### ISSUE TITLE
Update Node version

### ISSUE THREAD

**Issue by jpcmf** [strapi-community/strapi-provider-upload-google-cloud-storage#155]
It's possible to update the version of Node in the `package.json`?

Today the package force us to use Node version 16. For some security reasons and future support of Node 16 it would be good to update the support version of Node in the package.

Today the engine configuration is:

`
"engines": {
    "node": "16",
    "npm": "8"
  },
`

I recommend to update the engine configuration to:

`
"engines": {
    "node": ">=16.19.0 <=18.x.x",
    "npm": "8"
  },
`

If you agree, I can open a pull request.

cc @Lith 

Thank you :)

**Comment by Lith** [comment]
Hello @jpcmf  !

Yes of course, do it ;) 

Thanks 👍

**Comment by jpcmf** [comment]
Hello @Lith! How are you? 
Np ;) But it seems that I can't open PR. It's blocked.

**Comment by Lith** [comment]
Hello 👋 
Have you fork the project on your own GitHub spaces ?
You will be allow to purpose PR from the forked project, but it's not possible directly from the main project.
Thx !

**Comment by JohnGale87** [comment]
I'm running into something similar,

npm is pinned to 8 but I'd like to use 9.

I looks like this was intentionally changed at somepoint:
https://github.com/strapi-community/strapi-provider-upload-google-cloud-storage/commit/ebc03c672f0e5dbbbb23f2450af9deadbd5ea9ae

Are you able to modify your PR to also allow an updated npm?

**Comment by Lith** [comment]
Fixed with #160 and publish in latest release 4.6.1
