### ISSUE TITLE
Custom image optimization formats

### ISSUE THREAD

**Issue by ciriousjoker** [strapi-community/strapi-provider-upload-google-cloud-storage#161]
**Is your feature request related to a problem? Please describe.**
We want to upload the highest quality raw footage to Strapi and still get fast page load times.

**Describe the solution you'd like**
-  based on some parameters
- We'd like to specify a list of formats like this:
  - `"large", jpeg, 80% quality, 1920w`
  - `"medium", webp, 60% quality, 512w`
  - ...
- "1920w" means the image is supposed to be scaled down until it's fits in a 1920x1920px square
- This extension should automatically generate optimized images based on the list of "target formats"
- When changing the list of formats, the extension should recreate all missing files. Example: jpeg 80% is deleted and recreated from the uploaded original file so it becomes jpeg 60% or whatever we changed it to
- The api response should be consistent with the given name, ie "large" should resolve to the jpeg 80% image on one day and if we decide to lower it later, the field should still be called "large", just the url should be different (preferably same url, but doesn't really matter)

**Describe alternatives you've considered**

Switch to Strapi's internal image provider and use dynamic resizing via one of the plugins in combination with a CDN.

**Comment by Lith** [comment]
Hi,

You need to use a third service like [CloudImage](https://www.cloudimage.io/en/home) to manage this (free usage available).

GCP is not a CDN, it's a storage bucket.
Strapi has implemented a custom CDN, but it's not useful, I suggest you to use an other service.

Thanks,
